### ISSUE TITLE
Add informative error message for no shortuuid

### ISSUE THREAD

**Issue by fredcallaway** [NYUCCL/whoops_yall#8]
I accidentally installed shortuuid for the wrong python interpreter, and I got this cryptic message:

```
[psiTurk server:off mode:live #HITs:6]$ server on
Experiment server launching...
Now serving on http://localhost:22362
Traceback (most recent call last):
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/psiturk/experiment_server.py", line 92, in <module>
    launch()
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/psiturk/experiment_server.py", line 89, in launch
    ExperimentServer().run()
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 206, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 302, in halt
    self.stop()
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 347, in stop
    time.sleep(0.1)
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/miniconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

Installing shortuuid fixed it. Is it possible to check that uuid is installed and provide a better error message?

**Comment by deargle** [comment]
server.log would have reported to you that shortuuid was missing.
